# This app just sleeps :)
apiVersion: v1
kind: Pod
metadata:
  name: sleepy-yaml
  labels:
    app: sleepy
    tier: some-serious-slacker-backend # :)
    version: "1.0"
spec:
  containers:
  - name: sleepy-yaml
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 60; echo -en Zzz; done;" ]
