
# transform docker-compose into k8s via:
# 1 .kompose.io (fatto da noi), oppure
# 2. compose2kube - meh 

run-joomla:
	docker-compose docker_compose_joomla.yml


compose2kube:
	# needs installing
	compose2kube -compose-file docker-compose.yml -output-dir output
