# copied from: https://stackoverflow.com/questions/30063907/using-docker-compose-how-to-execute-multiple-commands
# (note, compose file has to be of version '2' type):

# first
db:
  image: postgres
# third
web:
  image: app
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
  depends_on:
    - migration
# second (see depends_on)
migration:
  build: .
  image: app
  command: python manage.py migrate
  volumes:
    - .:/code
  links:
    - db
  depends_on:
    - db