# septober-service.yaml
# Let's suppose I have one better version
apiVersion: v1
kind: Pod
metadata:
  name: septober-v12
  namespace: riccardume
  labels:
    app: septober
    version: "1.2"
    tier: web-frontend
    #description: "Ruby app by Ricc"
    maturity: draft
    env: staging
    type: RubyOnRails
    #repo-url: 'https://github.com/palladius/septober'
    #docker-url: https://hub.docker.com/r/palladius/septober/
spec:
  containers:
  - name: septober-v12
    image: palladius/septober:v1.2
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "cd /home/riccardo/git/septober/ && make run" ]
