
# from https://docs.docker.com/compose/rails/#define-the-project

#version: '3' # originale ma non funge su Masagno :/
version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    environment:
      - GIC=${GIC}
      - FAKE_HOSTNAME="fake-${HOSTNAME}"
      #- FAKE_HOSTNAM2="fake-$HOSTNAME"
      - DEBUG=1
      - ANSWER=42
      - URL=${MUNCH_URL}
      - TAG_FROM_DOT_ENV=${TAG}
      - VERSION=${VERSION}
    volumes:
      - .:/myapp
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
