apiVersion: v1
kind: Pod
metadata:
  name: sleepy-ricc1
spec:
  containers:
  - name: sleepy-ricc2
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 60; echo -en Zzz; done;" ]
