# instructions: https://stackoverflow.com/questions/36554810/how-to-link-folder-from-a-git-repo-to-another-repo



# this is more for incremental adds - you should never run this
dont-run-me-once-for-all:
	git submodule add https://github.com/palladius/pasta
	git submodule add https://github.com/palladius/sakura
	git submodule add https://github.com/palladius/septober
	git submodule add https://github.com/palladius/addressbook
	git submodule add https://github.com/palladius/orgie
	git submodule add https://github.com/palladius/riccardo_nifty_store


