


show-databases:
	gcloud --project ric-cccwiki sql databases list --instance=prod

show-operations:
	gcloud --project ric-cccwiki sql operations list --instance=prod

describe-prod-db:
	gcloud --project ric-cccwiki beta sql instances describe prod

configure-firewall:
	./configure-firewall.sh