# Riccardo PRIVATISSIMO
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  encoding: utf8
  database: ricniftystore
  username: ricniftystore 
  password: templatissimo 
  host: 35.198.182.127
  port: 3306
