apiVersion: v1
kind: Secret
metadata:
   name: db-credentials
type: Opaque
data:
  mysql-root-password: VGVzdDEyMzQK # Test1234
  mysql-user: dGVzdGFkbQo= # testadm
  mysql-password: VGVzdDEyMzQK # Test1234

# https://stackoverflow.com/questions/45650044/cant-connect-to-mysql-pod-in-kubernetes-when-using-secrets-for-password-access
