joomla:
  image: joomla
#  links:
#    - joomladb:mysql
  ports:
    - 10080:80
  volumes:
    -  /srv/docker/riccardojumlaproject/joomla:/var/www/html
    -  /srv/docker/riccardojumlaproject/logs/joomla:/var/log
  environment:
    #JOOMLA_DB_PASSWORD: "Ricc4rd0neSc0piazz4to"
    JOOMLA_DB_HOST: 104.197.195.148:3306
    JOOMLA_DB_USER: jumla3user
    JOOMLA_DB_PASSWORD: DibbiVerginelloXOra
    JOOMLA_DB_NAME: palladiusit_jumla3
    # PowerUser: palladius // Jumla3NewPwd
  restart: always

#joomladb:
#  image: mysql:5.6
#  environment:
#    MYSQL_ROOT_PASSWORD: "Ricc4rd0neSc0piazz4to"
#  volumes:
#    - /srv/docker/riccardojumlaproject/mysql:/var/lib/mysql
#  ports: #This is exposed in case you want to login to the mysql from the docker host. It is not mandatory to expose it.
#    - 10306:3306
#  restart: always

# The below phpmyadmin is optional. Remove it if you do not require it.
# Never expose phpmyadmin to the internet!
phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 10081:80
    volumes:
     - /srv/docker/riccardojumlaproject/phpmyadmin/sessions:/sessions
#    links:
#     - joomladb:mysql
