FROM joomla

#COPY goliardia-files/* /var/www/html/
# cp -R /usr/src/joomla/ /var/www/html/
# COPY config/configuration.php /var/www/
#RUN ls /var/www/html/ # debug

#RUN mv /var/www/installation /var/www/installation-sticazzi
#RUN touch /var/www/RICCARDO_WAS_HERE.touch

EXPOSE 80 
