apiVersion: v1
kind: Service
metadata:
  labels:
    app: ricniftystore
  name: ricniftystore-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ricniftystore
