apiVersion: v1
kind: Pod
metadata:
  name: riclife-v092-test
spec:
#  volumes:
#  - name: shared-data
#    emptyDir: {}
  containers:
  - name: riclife-v092
    image: gcr.io/ric-cccwiki/riclife:v0.9.2 
#    volumeMounts:
#    - name: shared-data
#      mountPath: /usr/share/nginx/html
