
# docs: https://github.com/kubernetes/kubernetes/tree/release-1.6/examples/guestbook
status:
	kubectl get pods,rc,svc -L app

up:
	kubectl create -f ./

down:
	kubectl delete -f ./

logs:
	kubectl logs -f POD-NAME
