
status:
	kubectl get pods | egrep "mysql|wordpress"
	kubectl get pv
	kubectl get secrets
	kubectl get services wordpress


up:
	MYSQL_ROOT_PASSWORD=M4k3f1l3P4S5w0rd ./spin-up.sh

down:
	./spin-down.sh


