# Changed name to  mysql-persistent-storage3
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql3
  labels:
    app: mysql3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql3
  template:
    metadata:
      labels:
        app: mysql3
    spec:
      containers:
        - image: mysql:5.6
          name: mysql3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql3
          volumeMounts:
            - name: mysql-persistent-storage3
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage3
          gcePersistentDisk:
            pdName: mysql-disk3
            fsType: ext4
